name: neuro_tribo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Ícones
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0

  # Vídeo e Áudio
  video_player: ^2.8.1
  chewie: ^1.7.1
  audioplayers: ^5.2.1
  
  # Utilitários
  url_launcher: ^6.2.5
  timeago: ^3.6.1
  image_picker: ^1.0.7 # PARA PEGAR FOTOS DA GALERIA

  # Firebase e Backend
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.9 # PARA SALVAR AS FOTOS NA NUVEM
  google_sign_in: ^6.2.1
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/