name: neuro_tribo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Ícones
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0 # Ícones do Google/Facebook

  # Vídeo
  video_player: ^2.8.1
  chewie: ^1.7.1

  # Firebase e Autenticação
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1 # Versão estável para Web/Android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/