name: neuro_tribo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Ícones
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0

  # Vídeo e Áudio (NOVO)
  video_player: ^2.8.1
  chewie: ^1.7.1
  audioplayers: ^5.2.1 # Pacote de sons
  youtube_player_iframe: ^5.1.2

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Registrar pastas de arquivos
  assets:
    - assets/images/
    - assets/audio/ # Pasta nova de sons